# Generated by Django 2.1.7 on 2019-06-25 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('atendimento', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=9)),
                ('assunto', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=10)),
                ('profissao', models.CharField(max_length=100)),
                ('encaminhamento', models.CharField(max_length=100)),
                ('responsavel', models.CharField(max_length=100)),
                ('situacao', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.Empresa')),
            ],
        ),
    ]
