# Generated by Django 2.1.7 on 2019-06-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demanda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='assunto',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='situacao',
            field=models.CharField(max_length=10),
        ),
    ]
